### ISSUE TITLE
Broken link for meme 4.9.1

### ISSUE THREAD

**Issue by dence** [steuernb/NLR-Annotator#1]
Hi, the link in the README gives a "ERR_NAME_NOT_RESOLVED" error. The meme suite, including 4.9.1, is accessible here: http://meme-suite.org/index.html

Regards,
Daniel Ence

**Comment by steuernb** [comment]
Hi Daniel,
Thanks for letting me know! I fixed the link.
All the best
Burkhard

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/71259955-a171f500-2374-11ea-859d-f9a37afddd19.png)
I downloaded the software of meme-5.0.1 but I didn't find the bin directory and the mast in that directory,
I hope you can guide me

**Comment by steuernb** [comment]
Dear duhuipeng, your comment does not really belong into this issue.
I hope, with "downloaded" you also mean install. Using meme-suite versions newer than 4.9.1 is still experimental. But feel free to try using this branch https://github.com/steuernb/NLR-Annotator/blob/nlr_parser3/NLR-Parser3.jar

**Comment by duhuipeng** [comment]
![image](https://user-images.githubusercontent.com/58722433/71261167-a5534680-2377-11ea-8a5e-6136ca7186f4.png)
After downloading the link you gave me, I still got this error, saying that I didn't find it, mainly because the bin directory under my me software didn't .

**Comment by duhuipeng** [comment]
I can't find this bin directory path. Do you know what the problem is?
![image](https://user-images.githubusercontent.com/58722433/71261569-aa64c580-2378-11ea-9ed6-88dd09b49463.png)

**Comment by steuernb** [comment]
I believe, you did not install the meme-suite properly. Not all software for linux is pre-compiled. You somtimes need to do  a bit more than just downloading and extracting.

**Comment by duhuipeng** [comment]
I don't quite understand what you mean. Can you make it clear? I downloaded meme4.9.1. from the URL you gave me. Follow the steps you prompted, but the bin directory could not be found
![image](https://user-images.githubusercontent.com/58722433/71263182-5f4cb180-237c-11ea-8f8d-f4b159f6ca75.png)
![image](https://user-images.githubusercontent.com/58722433/71263305-9c18a880-237c-11ea-8215-90ba894adf6f.png)
