### ISSUE TITLE
CalculateNLRGenes

### ISSUE THREAD

**Issue by qing1990** [steuernb/NLR-Annotator#10]
Hi Burkhard, 
 
I am trying to compare my NLR loci with gene annotation, but I couldn’t find the Java program CalculateNLRGenes.java (https://github.com/steuernb/wheat_nlr). Could you tell me where this file is? Thank you very much.
 
Best reguards
 
Qing

**Comment by steuernb** [comment]
Hi Quing, the link you mention above seems to work for me. It is in the java/src folder. The direct link is here: https://github.com/steuernb/wheat_nlr/blob/master/java/src/CalculateNLRGenes.java.
Please keep in mind that the code was meant to analyse a specific data data set and is published here for reproducibility matters. It is not a tool to check other data sets. If you want to compare loci with a gene annotation, it is essentially comparing two gff files along with a lot of tinkering and manual curation.

**Comment by steuernb** [comment]
Correction: It was not available before, my apologies! If fixed this now. Please let me know if there are still issues.

**Comment by qing1990** [comment]
Hi, Burkhard, 
Thanks for your suggestions and answers .
