### ISSUE TITLE
some questions about nlr3

### ISSUE THREAD

**Issue by cwu2011** [steuernb/NLR-Annotator#12]
hi I am trying to use NLR Annotation tools to search NLR genes. I have two questions, could you please show me how to solve them? thank you!
1、 Is the input file of ChopSequence in the first step a sequence file of the whole genome, or just a cds sequence file of the genome?
2、when I tried to NLR-Parser3.jar and NLR-Annotation, it did not work and return the message "Error: Invalid or corrupt jarfile NLR-Parser3.jar". The version of java and MEME on my computer is 1.8.0_144 and 5.0.1, separately.

**Comment by steuernb** [comment]
Hi,
1. The idea of ChopSequence is to run it on a whole genome. However, it will add a suffix to each sequence identifier, which is used by NLR-Annotator. So, if you want to use NLR-Annotator on CDS, you would still need to run the ChopSequence. That said, for CDS, you can just run NLR-Parser.
2. That sounds to me like the jar file you downloaded is corrupted. When you run `java -jar NLR-Parser.jar`, it should give you the input parameters. Please have a look if that works. Otherwise, could you post the command you use, please?

**Comment by cwu2011** [comment]
thanks for your reply!
i tried to download the two jar packages through different browser and download tools, and different computer(os: win10/ubuntu16.04). the problem of jar file invalid or corrupt was still there.
my command is 
java -jar NLR-Parser3.jar -t 4 -y (path to mast) -x (meme.xml) -i (chopped fasta file) -c (out.xml)
when I use the command java -jar NLR-Parser3.jar, the same error message returned.

is it possible that the jar files archived on github are incomplete, due to network or server fault?

**Comment by steuernb** [comment]
Hm...not quite sure what is going on. When you download the ChopSequence.jar, does this run normally or are all jar files you download corrupt?

**Comment by cwu2011** [comment]
ChopSequence.jar runs normally.

**Comment by cwu2011** [comment]
I found NLR Parser3 can be run on my ubuntu workstation. 
Is NLR Annotation tools only support linux?

**Comment by steuernb** [comment]
I have run it on CentOS and MacOS. This is Java, so it should be platform independent.

**Comment by cwu2011** [comment]
Hi!
There is an Expection when I run NLR-Annotation.jar. the message is as below:
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at nlr_parser.MastMotifHit.<init>(MastMotifHit.java:66)
	at nlr_parser.MastMotifHitList.<init>(MastMotifHitList.java:59)
	at nlr_annotator.NLR_Annotator.readXML(NLR_Annotator.java:488)
	at nlr_annotator.NLR_Annotator.<init>(NLR_Annotator.java:70)
	at nlr_annotator.NLR_Annotator.main(NLR_Annotator.java:1921)
	... 5 more

My command is 
java -jar NLR-Annotator.jar -i ./NLR_Parsed3.out.xml -o NLR-Annotator.out.txt

Do you know what happened?

**Comment by cwu2011** [comment]
Are there any differences between the two ChopSequence.jar  in pages of pre version of NLR-tool and current NLR-tool3?
I downloaded the ChopSequence.jar file from pre version page and got a chopped genome sequence file by running this package.
can i use this chopped fasta file on current version NLR-Parse3.jar?
(ChopSequenct.jar downloaded from the page of current version is not able to run on my station it returns the message of invalid of currupt jarfile.)

**Comment by steuernb** [comment]
Hi,
For the ChopSequence, it does not matter where you download it from. This has not changed. If you use the NLR-Parser3 you also need to use the NLR-Annotator from the same repository.

**Comment by cwu2011** [comment]
I found the new version of NLR tools does not work normally on my machines, so I finally chose V0.7 to search NLR genes in my project.
thanks for your reply!

**Comment by Kapeel** [comment]
I had the same issue with NLR-Parser3. I think I had downloaded the NLR-Parser3.jar from the link but just cloning the branch `git clone -b nlr_parser3 https://github.com/steuernb/NLR-Annotator.git` with all the files in it and then running resolved it

**Comment by acread** [comment]
I was having similar issues and Kapeel's solution worked for me.
