### ISSUE TITLE
motif definition file meme.xml

### ISSUE THREAD

**Issue by xingkunj** [steuernb/NLR-Annotator#14]
Hi Steuernagel:

I am looking for a suitable tool to capture and annotate NLR from fish genomes, and I'm interested in NLR-Annotator. But before I could try it, is NLR-Annotator only suitable for NLR-associated motifs from plant genome (according to the motif definition file 'meme.xml')? As NLRs sometimes cause mis-assembly/annotations in animal genomes too, is it possible to use customized motif training dataset, for instance, using NACHT domain (or relevant ones) from animal genome?  If so, how to prepare such customized meme.xml? Many thanks!

Kun

**Comment by steuernb** [comment]
Hi Kun,
I am afraid, NLR-Annotator would not work for Fish genomes. The code is tied to the plant-specific motifs. Of course, it would be possible to use the same concept for you but you would need to define your own set of motifs, then change NLR-Annotator source code to work with your set of motifs. This would take some significant time to develop.
As an easier approach, you could take your genome(s) and chop it up into overlapping fragments. Then you 6-frame translate every fragment and run HMM-Scan with the Pfam domains. It will take much more compute time than NLR-Annotator but with a little bit of tinkering you could get similar results.
all the best
Burkhard

**Comment by xingkunj** [comment]
Hi Burkhard
Thanks for quick response and suggestions, will think about it!
Cheers
Kun
