### ISSUE TITLE
What's the difference between NLR-Parser and NLR-Annotator?

### ISSUE THREAD

**Issue by CAShuangchao** [steuernb/NLR-Annotator#20]
Dear Developers,
Are there any differences of NLR-Annotator and NLR-Parser? They all use Nlr-parser.jar.

**Comment by steuernb** [comment]
NLR Parser is to classify a sequence if it is associated with NLR or not. NLR-Annotator tells you where the NLR associated loci are within a sequence. So, running Parser on say wheat chromosome 1A, NLR-Parser only tells you "yes there is at least one NLR on it". 

You have a set of CDS, NLR-Parser is sufficient. You have a genome sequence, use NLR-Annotator.

hope this helps...
cheers
Burkhard

**Comment by CAShuangchao** [comment]
Great software, very responsible developer, thank you.


Original ------------------
From: Burkhard Steuernagel ***@***.***&gt;
Date: Fri,May 28,2021 10:49 PM
To: steuernb/NLR-Annotator ***@***.***&gt;
Cc: CAShuangchao ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [steuernb/NLR-Annotator] What's the difference between NLR-Parser and NLR-Annotator? (#20)





 
NLR Parser is to classify a sequence if it is associated with NLR or not. NLR-Annotator tells you where the NLR associated loci are within a sequence. So, running Parser on say wheat chromosome 1A, NLR-Parser only tells you "yes there is at least one NLR on it".
 
You have a set of CDS, NLR-Parser is sufficient. You have a genome sequence, use NLR-Annotator.
 
hope this helps...
 cheers
 Burkhard
