### ISSUE TITLE
NLR-Parser error

### ISSUE THREAD

**Issue by zhangjijin** [steuernb/NLR-Annotator#24]
Hello, I encountered an error while using NLR-parser.jar.
Instead of stopping, the program just keeps running and never stops.
My JRE is 1.8. I used the test data you provided
![image](https://user-images.githubusercontent.com/44020726/131459046-edc09f68-1491-4185-a5c6-b83434250ba4.png)

**Comment by steuernb** [comment]
Hi,
my first guess is that you are using the NLR-Parser from the main release together with a MEME version above 4.9. If that is the case, please try again using the jars from here: https://github.com/steuernb/NLR-Annotator/tree/nlr_parser3.

If this is not the case, it would be helpful to have a look at your input fasta. 
all the best
Burkhard
