### ISSUE TITLE
Problem of meme intallation

### ISSUE THREAD

**Issue by ttolessa** [steuernb/NLR-Annotator#3]
Dear sir,
I was trying to install the compatible MEME version 4.9.1 program for NLR_Parser to start resistance gene anotation.

I used the following command line.

./configure --prefix=$HOME/meme --with-url=http://meme-suite.org/

still fine but after running the 'make' command line, I am geting the following error reports:

Makefile:1548: recipe for target 'glam2' failed
make[4]: *** [glam2] Error 1
make[4]: Leaving directory '/home/tamene/downloaded_programs/meme_4.9.1/src'
Makefile:4377: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/tamene/downloaded_programs/meme_4.9.1/src'
Makefile:1399: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/tamene/downloaded_programs/meme_4.9.1/src'
Makefile:341: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/tamene/downloaded_programs/meme_4.9.1'
Makefile:272: recipe for target 'all' failed
make: *** [all] Error 2

I am looking for support if you may also have a pre-compiled MEME vesion.

Thank you,
Tamene

**Comment by steuernb** [comment]
Dear Tamene,
I am afrain, I cannot help you with this issue. My program is using the meme-suite, but I do not develop or maintain it. Maybe you can contact the develpers of meme? http://meme-suite.org/doc/authors.html?man_type=web
all the best
Burkhard

**Comment by ttolessa** [comment]
Hi Burkhard,

Can you may be help in sharin your pre-compiled version please.
Thanks you
Tamene

**Comment by steuernb** [comment]
Dear Tamene,
There are lots of reasons why I do not want to do this, not least of them is my uncertainty regarding their licensing. 
I suggest, you go through the installation process again following their help (http://meme-suite.org/doc/install.html?). Make sure you have installed all the pre-requisites. The last section of the install guide from meme contains the contact information for further help.
all the best
Burkhard

**Comment by BenjaminSchwessinger** [comment]
Hi Burkhard. We now fixed the installation of meme 4.9.1 it is a bit of a mess as it is super old and not compatible as such with most up-to-date compilers. Anyway we got it to work but would like to see if it works on a test set and provides the correct output. Could you share a small test set and expected output with us please.

This would help to make sure all is good before going ahead with many other genomes.

Thanks!
Benjamin

P.S.: To get meme 4.9.1 to compile you need to change the following according to Charles E Grant <cegrant@uw.edu> Thanks!.

If you have to use version 4.9.1, then the easiest fix is to change the definition of report_external_failure in glam2_glam2.c (line 148) from 

inline void report_external_failure(const char *prog, int status) {

to

static inline void report_external_failure(const char *prog, int status) {

P.P.S.: Any chance of updating to a newer version of meme?

**Comment by steuernb** [comment]
Hi Benjamin and Tamene,
Benjamin, thanks for posting the help! 
It sounds like the old meme version is difficult to maintain, so I guess I have to give in. I started writing the interface to the newer meme version. There is already a hacky version that works in principal. It just needs to be tidied up and tested. Please send me an email if you are happy to test it.

**Comment by steuernb** [comment]
I have added a branch nlr_parser3 with some code that should work with up-to-date meme-suite versions. There is also an updated jar file and some sequences to test the new NLR-Parser.

**Comment by ttolessa** [comment]
Hi Burkhard,
Thanks,
Let us give a try and we will let you know the outcome
Tamene
