### ISSUE TITLE
Error: Invalid or corrupt jarfile NLR-Annotator-v2.1b.jar

### ISSUE THREAD

**Issue by theskeptics** [steuernb/NLR-Annotator#31]
Hi, Sir, 

When I try to use NLR annotator, following message pops up
#===========================================
XXXX:~/Apps/NLR-Annotator$ java -jar NLR-Annotator-v2.1b.jar
Error: Invalid or corrupt jarfile NLR-Annotator-v2.1b.jar
#===========================================

could you let me know what happen?

Jar file size is  204494.

**Comment by steuernb** [comment]
Hi, thanks for the comment. Does this happen with this jar file only or with other jar files as well? Some corporate firewalls will corrupt the jar file.
I have just downloaded the file and tested. It is not corrupt.
size: 552663
md5sum: 9b721c3936cb3d57ec04f9c99c1bd843
*    You could try to compile from source.
*    You could ask your computing department for help
*    If you trust this webpage, you could download the file at home, test it in a safe environment, then bring it to work on a USB stick. (In terms of cybersecurity, this last option is dangerous!)

best wishes
Burkhard

**Comment by theskeptics** [comment]
I got it
working perfect.

Actually, the size is different.
Maybe something happen during download.

Thanks a lot

**Comment by steuernb** [comment]
could you add a comment how you got it working, please? That might help other users.
Did you get the same MD5sum or is that different as well? 
thanks
Burkhard

**Comment by theskeptics** [comment]
File size issue!!

Something happen during downloads
Plz. check th file size. It should be 552663
My broken file size is 204494.

Thanks a lot

**Comment by bmansfeld** [comment]
I had this error when I `wget`-ed the "copy permalink" link from github.
To resolve, I downloaded the file on my computer and ftped it over to my cluster.
Not sure why the jar that comes from the permalink isn't right???
Just FYI

**Comment by steuernb** [comment]
Thanks for the comment!

Hm. it works for me.
Are we talking about the same link?
`wget https://github.com/steuernb/NLR-Annotator/blob/5d7f1ecfae8927f34baa1126998ccc9869995784/NLR-Annotator-v2.1b.jar`

I think the issue is not the github link but that some cyber security settings will not let jar files be downloaded. 

Your workaround is the way to go if you trust the source (thanks for the trust! ;-) )
