### ISSUE TITLE
NLR-parser program

### ISSUE THREAD

**Issue by ttolessa** [steuernb/NLR-Annotator#5]
Dear Burkhard,

I am trying to run the NLR-parser program to get the .xml output to be used for the NLR-Annotator, however, I am getting the following message. 

This is the command I used:
 java -jar ~/athaliana/scripts/NLR-Parser.jar -t 10 -y ~/anaconda3/envs/NLR_Annotator/bin/meme_4.9.1/bin/mast -x ~/athaliana/scripts/meme.xml -i ~/athaliana/atproteome/anoutput1/choppingseq.fasta -c ~/athaliana/atproteome/anoutput1/NLR_parser_output.nlr.xml

This is the response:
Using meme.xml from /home/tamene/athaliana/scripts
DEBUG: Temporary directory is /home/tamene/temp_mast63013306
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at nlr_parser.MastMotifHit.<init>(MastMotifHit.java:32)
        at nlr_parser.MastEntry.<init>(MastEntry.java:58)
        at nlr_parser.MastXMLReader.readEntry(MastXMLReader.java:97)
        at nlr_parser.MastFile.readEntries(MastFile.java:44)
        at nlr_parser.MastFile.<init>(MastFile.java:39)
        at nlr_parser.MastParallelExecuter.executeMastProtein(MastParallelExecuter.java:213)
        at nlr_parser.NLRParser.<init>(NLRParser.java:48)
        at nlr_parser.NLRParser.main(NLRParser.java:193)
        ... 5 more

What is going wrong with my usage? I have installed all the dependencies correctly. I also tried to use mast.xml instead of mast but still not working.

With kind regards,
Tamene

**Comment by steuernb** [comment]
Hi Tamene,
Can you run your mast on its own with the meme.xml and some random NLR amino acid sequence? That is just to make sure mast is working.
I am not entirely sure what is going wrong. Would you be able to share your input sequences? Are there any empty sequences ( two consecutive lines both starting with >) or sequences with lots of IUPAC bases?

**Comment by ttolessa** [comment]
Dear Burkhar,

Thanks for your prompt response.
I am using the protein sequence (Athaliana_167_TAIR10.protein.fa) of Arabidopsis thaliana from Phytozome13 (Annotation sub-folder) as a trial input. You can download it from Phytozome13. It looks that the Chopped Sequence file has too many gaps of indeterminate lengths. I copied parts of it as follows:

>ATCG01020.1_0
MAVPKKRTSISKKRIRKKIWKRKGYWTSLKAFSLGKSLSTGNSKSFFVQQNK*
>ATCG01060.1_0
MSHSVKIYDTCIGCTQCVRACPTDVLEMIPWDGCKAKQIASAPRTEDCVGCKRCESACPTDFLSVRVYLWHETTRSMGLAY*
>ATCG00330.1_0
MAKKSLIYREKKRQKLEKKYHLIRRSSKKEISKIPSLSEKWKIHGKLQSPPRNSAPTRLHRRCFSTGRPRANYRDFGLSGHILREMVQACLLPGATRSSW
*
>ATCG00800.1_0
MGQKINPLGFRLGTTQSHHSLWFAQPKKYSEGLEEDKKIRDCIKNYVQKNIRISSGMEGIARIEIQKRIDLIQIIIYMGFPKLLIEDKPRRVEELQMNVQ
KELNCVNRKLNIAITRISNPYGDPNILAEFIAGQLKNRVSFRKAMKKAIELTEQANTKGIQVQIAGRIDGKEIARVEWIREGRVPLQTIEAKIDYCSYTV
RTIYGVLGIKIWIFVDEE*
>ATCG00710.1_0
MATQTVEDSSRSGPRSTTVGKLLKPLNSEYGKVAPGWGTTPLMGVAMALFAVFLSIILEIYNSSVLLDGISVN*
>ATCG00590.1_0
MPTITSYFGFLLAALTITSVLFIGLSKIRLI*
>ATCG01050.1_0
VYLVFTTNDFPWLTIIVVFPISAGSLMLFLPHRGNKVNKWYTICICILELLLTTYAFCYNFKMDDPLIQLSEDYKWIDFFDFYWRMGIDGLSIGTILLTG
FITTLATLAAFPVTRDSRFFHFLMLAMYSGQIGSFSSRDLLLFFIMWELELIPVYLLLSMWGGKKRLYSATKFILYTAGSSIFLLIGVLGISLYGSNEPT
LNLELLANKSYPVTLEILFYIGFLIAFAVKSPIIPLHTWLPDTHGEAHYSTCMLLAGILLKMGAYGLVRINMELLPHAHSMFSPWLLVVGTIQIIYAAST
SPGQRNLKKRIAYSSVSHMGFIIIGISSITDPGLNGAILQIISHGFIGAALFFLAGTSYDRIRLVYLDEMGGMAISIPKIFTMFTILSMASLALPGMSGF
IAEFIVFFGIITSQKYFLISKIFIIFVMAIGMILTPIYLLSMLRQMFYGYKLINIKNFSFFDSGPRELFLSISILLPIIGIGIYPDFVLSLASDKVESIL
SNYFYG*
>ATCG00050.1_0
MVKLRLKRCGRKQRAVYRILAIDVRYRREGRDLSKVGFYDPITNQTFLNLSAILDFLKKGAQPTRTAHDISKKAGIFTE*
>ATCG00520.1_0
MSWRSESIWIEFITGSRKTSNFCWAFILFLGSLGFLLVGTSSYLGRNVISLFPSQQIIFFPQGIVMSFYGIAGLFISCYLWCTILWNVGSGYDLFDRKEG
IVRIFRWGFPGKSRRIFLRFFMKDIQSIRIEVKEGVSARRVLYMEIRGQGAIPLIRTDENFTTREIEQKAAELAYFLRVPIEVF*
>ATCG00070.1_0
MLNIFNLICIFFNSTLFSSTFLVAKLPEAYAFLNPIVDVMPVIPLFFLLLAFVWQAAVSFR*
>ATCG00700.1_0
METATLVAIFISGLLVSFTGYALYTAFGQPSQQLRDPFEEHGD*
>ATCG00830.1_0
MAIHLYKTSTPSTRNGAVDSQVKSNPRNNLICGQHHCGKGRNARGIITARHRGGGHKRLYRKIDFRRNAKDIYGRIVTIEYDPNRNAYICLIHYGDGEKR
YILHPRGAIIGDTIVSGTEVPIKMGNALPLTDMPLGTAIHNIEITLGRGGQLARAAGAVAKLIAKEGKSATLKLPSGEVRLISKNCSATVGQVGNVGVNQ
KSLGRAGSKCWLGKRPVVRGVVMNPVDHPHGGGEGRAPIGRKKPVTPWGYPALGRRTRKRKKYSETLILRRRSK*
>ATCG00480.1_0

Kind regards,
Tamene

**Comment by steuernb** [comment]
Hi Tamene,
NLR-Annotator is not really made for amino acid sequences. Try running it on the nucleotides. I have not really worked on the amino acid side since the original NLR-Parser publication. So, that is what you want to run if you want to classify amino acid sequences: https://github.com/steuernb/NLR-Parser. 
cheers
Burkhard

**Comment by ttolessa** [comment]
Dear Burkhard,

Sorry for the misunderstanding. Now worked with the nucleotide sequence.
Thanks,
Tamene

**Comment by steuernb** [comment]
No worries. Thanks for using my tool! Let my know if I can help in any way.
cheers
Burkhard
