### ISSUE TITLE
NLR parser not producing XML output file

### ISSUE THREAD

**Issue by G-Thomson** [steuernb/NLR-Annotator#7]
Hi Burkhard

I am using the nlr_parser3 branch to annotate NLR genes on Citrus genomes. However when I run NLR-Parser the job keeps on running and no XML output file is produced.

It appears to identify motifs in the chopped sequences fairly quickly and store them in a directory called `temp_mast1` and I have checked that all the chopped sequences are represented in there. But then nothing happens.

I initially tried doing an entire 328 Mb genome and let it run for two days before stopping it. I have then tried just one chromosome of a different genome and while the Mast sequences are all there the job is still running.  

Here is an example of the command I am running:
`java -jar /home/NLR-Annotator/NLR-Parser3.jar -t 5 -y /root/meme/bin/mast -i /home/ChopSequences/chopped_1.fa -c /home/Parser/Parsed_1.xml`

I am running these inside docker containers based on Ubuntu 18.04 on 1 CPU, 2GB RAM cloud instances which look fine in terms of memory.

Is it obvious what I'm missing?

**Comment by steuernb** [comment]
Hi Geoffrey,
it is not obvious, no. There should be no problem for any size of input genome. Which meme version are you using? What is the length of the chopped fragments? 
If you use only 1 CPU, -t makes more sense to be 1, but that should not be a problem. 
Can you run it again, explicitely using the -x meme.xml (download here: https://github.com/steuernb/NLR-Annotator/releases/download/v0.7-beta/meme.xml), please? If you don't set the -x parameter, NLR-Parser tries to find it but if it does not, the error message is not explicit enough. I need to fix that. Please let me know if that helps.
All the best
Burkhard

**Comment by G-Thomson** [comment]
Hi Burkhard

That did the trick. Using the `meme.xml` file you linked got it working.

Thank-you for your help!

**Comment by steuernb** [comment]
Thanks for the feedback! I will put better checks for this into the next version.
