### ISSUE TITLE
NLR-Parser does not produce result

### ISSUE THREAD

**Issue by esud1** [steuernb/NLR-Annotator#8]
Hi Burkhard, 

I am having a problem with the NLR-Parser step after running the ChopSequence step. 
It never produces a result, even after I left it running for a week. 
I tried to use the NLR-Parser3, along with a newer meme version, but still having the same problem. 
So I am currently testing it with the provided Rgenes.fasta example, and it has been running for two days without producing XML data. 

However, it does produce file in the temp_mast1/ folder, but nothing happens after that. 

I have read a previous issue that is resolved after providing `meme.xml` to the command, but it does not seem to help with my problem. 

Can you please advise how to resolve the problem? 

Thanks, 
Edi

**Comment by steuernb** [comment]
Hi Edi,
can you provide the command line call, please? At one point we might also need to know the system you are working on and the versions of jre and meme.
First thing to check is that MAST works on its own. Download a random NLR protein (e.g. AGQ17382.1) and run MAST with the provided meme.xml. The program call is something like `mast meme.xml Sr33.faa`. Let's see how that works.

**Comment by esud1** [comment]
Hi Burkhard,

The command line that I used was: 
`java -jar /path/to/NLR-Parser3.jar -t 8 -y /path/to/mast -x ./meme.xml -i Rgenes.CDS.fasta -c Rgenes.output.xml`

JRE version 1.8 
meme version 4.12.0 
I am running it in CentOS Linux 7

I tried running the MAST on its own using the provided meme.xml, but was returned this error message: 
```
Errors from MEME XML parser:
Expected state IN_USE_LLR not found!
FATAL: No motifs found in file "meme.xml".

```

Thanks for the help!

**Comment by amariagallego** [comment]
Hi Dr. Burkhard,

Cordial greeting. I have the same issue as Edi, I run MAST successfully, but later when I run NLR-Parser it gets stuck. Currently I got an issue with meme.xml file. I have six different paths for the meme.xml file into the meme folder. Could you provide me that path for meme.xml please? or Edi?

the code I run was


java -jar NLR-Parser3.jar -t 32 -y /home/adrianagallego/Documents/NRL_Annnotator/meme-5.1.0/bin/mast -x /home/adrianagallego/Documents/NRL_Annnotator/meme-5.1.0/tests/common/motif.Puf3p/meme.xml -i RgenesCDS_outputRedUniq.fasta -c output_parse5.xml

Thanks!

**Comment by steuernb** [comment]
@esud1: this sounds like the meme.xml you downloaded is corrupt. I have seen a few cases where the same happend but I am not sure why. Open the meme.xml in a text edito and check if this is sane xml. If you need help with that, please send your version of meme.xml to burkhard.steuernagel<at>jic.ac.uk. 
@amariagallego: If you get a proper output from running MAST on its own, this might be a different issue. Are you getting a nice html output where you can see the motifs in all sequences?

**Comment by amariagallego** [comment]
Dear Dr. Burkhard,

It worked perfectly. The issue was related with the meme.xml file. Here the script I run

java -jar NLR-Annotator.jar -i output_parse.xml -o output.nlr.txt

Best regards

**Comment by steuernb** [comment]
@esud1 : I could reproduce your error. I found an installation of meme-4.12.0 on our system. Running that with test data got me the same error, while verions meme-4.9.1 and meme-5.1.0 worked nicely! I did not install the problematic version myself so I cannot say if any essential part for mast was omitted there or if there is actually a problem with our meme.xml and v-4.12.0. 
Any chance you can install a newer meme version?

**Comment by esud1** [comment]
Hi Burkhard, 

Yes, I have just installed meme-5.1.1 and it works fine. Looks line v. 4.12.0 does have a problem with the program. 
Many thanks for the help! 

Edi
